### PR TITLE
Removed unnecessary ts:config task from gulp

### PR DESCRIPTION
**Pull request by kureta**
I also simplified tsconfig.json
I couldn't figure out how to get outDir from tsconfig.json but maybe keeping all path variables inside that one path gulp file is better anyway.

### CODE REVIEW

**Comment by jwhitaker** [comment]
Just made an update where I've removed gulp and replaced jspm with webpack.

**Comment by kureta** [comment]
It looks simpler this way. I am new to frontend development and I am trying to establish my tools. Your boilerplate is a real nice place to start. But I have one question: why don't you put your `index.html` file in `src/` folder?

**Comment by jwhitaker** [comment]
Mostly because I think it keeps things simpler.  You could absolutely keep it in the src folder and get things working that way.  You could even place it somewhere else and get it working that way.  I think keeping it located at the root opens up more options and keeps everything cleaner.  For example, if I wanted to access a module located in node_modules I can without any extra configuration.  It will also make going into production and running this behind an actual web server easier.

There is the consistence aspect as well.  During my research, I've seen a lot of people keeping it at the root folder as well.  

Hopefully that answers your question.

**Comment by kureta** [comment]
Yes it does, thank you. I thought it should be in src since it is part of the source code of your app but this makes sense.

**Pull request closed without merging**
